### ISSUE TITLE
This is not for jetpack-compose

### ISSUE THREAD

**Issue by TheFreezingChicken** [javaherisaber/FabSpeedDial#1]
Jetpack Compose is a library that uses composable functions, what you're using here is a normal View approach. Remove the tag and update your readme.

[Jetpack Compose](https://developer.android.com/jetpack/compose)

**Comment by javaherisaber** [comment]
@TheFreezingChicken 
Updated!
This is an old experimental project which I had been planning to add compose in early alpha or (dev) versions.
Which turned out to be forgotten.

Thanks for the reminder.
